# Generated by Django 5.0.6 on 2024-05-19 19:08

import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('celja_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('actual_stock', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_stock', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Cope')], default='kg', max_length=10)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('total_cost_per_product', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_revenue_per_product', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('buys', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'BLERJE'), ('sale', 'SHITJE')], default='buy', max_length=4)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='product.product')),
            ],
        ),
    ]
