# Generated by Django 5.0.6 on 2024-06-03 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='celja_quantity',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('previous_total_stock', models.IntegerField()),
                ('previous_sales', models.IntegerField()),
                ('celja', models.IntegerField()),
                ('previous_month_celja', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'unique_together': {('product', 'year', 'month')},
            },
        ),
    ]
